apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        env:
        - name: WEBPASSWORD
          value: "123456"
        ports:
        - containerPort: 53
          hostPort: 53
          name: tcp
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          name: udp
          protocol: UDP
        - containerPort: 80
          hostPort: 30003
          name: http
          protocol: TCP
      
