apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        env:
        - name: WEBPASSWORD
          value: "123456"
          name: TZ
          value: "America/NewYork"
        ports:
        - containerPort: 53
          hostPort: 53
          name: tcp
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          name: udp
          protocol: UDP
        - containerPort: 80
          hostPort: 30003
          name: http
          protocol: TCP
        volumeMounts:
        - name: etc
          mountPath: /etc/pihole
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d
      volumes:
        - name: etc
          hostPath:
            path: /etc/pihole
            type: Directory
        - name: dnsmasq
          hostPath:
            path: /etc/dnsmasq.d
            type: Directory
      securityContext:
        fsGroupChangePolicy: "OnRootMismatch"
