apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocipihole
spec:
  selector:
    matchLabels:
      app: ocipihole
  replicas: 1
  template:
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        resources:
        ports:
        - containerPort: 80
