apiVersion: apps/v1
kind: Deployment
metadata:
  name: oci-pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        ports:
        - containerPort: 80
        
