apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  selector:
    matchLabels:
      app2: pihole
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app2: pihole
        tier: frontend
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
